# Generated by Django 4.2.20 on 2025-04-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название кейса')),
                ('price', models.PositiveIntegerField(verbose_name='Цена кейса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'кейс',
                'verbose_name_plural': 'Кейсы',
                'default_related_name': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=128, verbose_name='Название оружия')),
                ('fullname', models.CharField(max_length=128, unique=True, verbose_name='Название скина')),
                ('price', models.IntegerField(verbose_name='Цена скина')),
            ],
            options={
                'verbose_name': 'скин',
                'verbose_name_plural': 'Скины',
            },
        ),
        migrations.CreateModel(
            name='SkinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('case', 'Кейс'), ('free_case', 'Бесплатный кейс'), ('upgrade', 'Апгрейд'), ('contract', 'Контракт'), ('present', 'Подарок'), ('change', 'Замена')], default='case', max_length=9, verbose_name='Источник получения скина')),
                ('action', models.CharField(choices=[('saled', 'Продан'), ('used_in_upgrade', 'Использован в апгрейде'), ('used_in_contract', 'Использован в контракте'), ('displayed_in_steam', 'Выведен в Steam'), ('changed', 'Заменен на другой'), ('none', 'Нет действий')], default='none', max_length=18, verbose_name='Действие со скином')),
                ('status', models.CharField(choices=[('in_inventory', 'В инвентаре'), ('in_process_to_output', 'В процессе на вывод'), ('output_error', 'Ошибка вывода'), ('succes_output', 'Успешно выведен в steam'), ('used_in_contract', 'Использован в контракте'), ('changed', 'Заменен на другой'), ('used_in_upgrade', 'Использован в апгрейде'), ('saled', 'Продан')], default='in_inventory', max_length=20, verbose_name='Состояние скина')),
                ('details', models.JSONField(verbose_name='Детали операции')),
                ('get_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время получения скина')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время использования скина')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.skin', verbose_name='Скин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'Транзакции',
                'default_related_name': 'skin_transactions',
            },
        ),
        migrations.CreateModel(
            name='CaseSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=10, default=1, max_digits=10, verbose_name='Шанс выпадения')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Кейс')),
                ('skin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.skin', verbose_name='Скин')),
            ],
            options={
                'db_table': 'case_skins',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='skins',
            field=models.ManyToManyField(through='cases.CaseSkin', to='cases.skin', verbose_name='Скины'),
        ),
    ]
