# Generated by Django 4.2.20 on 2025-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case/media/', verbose_name='Картинка кейса'),
        ),
    ]
