# Generated by Django 4.2.20 on 2025-05-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseskin',
            name='chance',
        ),
    ]
