# Generated by Django 4.2.20 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_caseskin_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='skin_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin/media/', verbose_name='Картинка скина'),
        ),
    ]
