# Generated by Django 4.2.20 on 2025-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_skin_skin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='rare',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
