# Generated by Django 4.2.20 on 2025-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_skin_rare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skintransaction',
            options={'default_related_name': 'skin_transactions', 'ordering': ('-get_at',), 'verbose_name': 'транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='skintransaction',
            name='details',
            field=models.JSONField(blank=True, verbose_name='Детали операции'),
        ),
    ]
