# Generated by Django 4.2.20 on 2025-04-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя из steam')),
                ('steam_id', models.CharField(max_length=17, unique=True, verbose_name='Идентификатор steam аккаунта пользователя')),
                ('steam_profile_url', models.URLField(verbose_name='Ссылка на steam профиль пользователя')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Ссылка на аватар пользователя в steam')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс игровой валюты')),
                ('trade_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Трейд-ссылка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
