# Generated by Django 4.2.20 on 2025-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trade_url',
            field=models.URLField(blank=True, default=None, null=True, unique=True, verbose_name='Трейд-ссылка'),
        ),
    ]
